Now it should correctly fail if some pipelinerun failed

diff --git a/integration-tests/pipelines/e2e-main-pipeline.yaml b/integration-tests/pipelines/e2e-main-pipeline.yaml
--- a/integration-tests/pipelines/e2e-main-pipeline.yaml
+++ b/integration-tests/pipelines/e2e-main-pipeline.yaml
@@ -87,7 +87,7 @@ spec:
               set -x
               echo "Running tests for OCP versions:"
               echo "$CONFIGS_JSON" | jq -r '.[][] | select(.key == "OCP").value'
-              failed_pipelines=0
+              pids=()
 
               while IFS= read -r version; do
                 (
@@ -108,15 +108,20 @@ spec:
                   pipelinerun_status=$(tkn pipelinerun describe "$pipeline_run_name" -o jsonpath='{.status.conditions[0].status}')
                   if [ "$pipelinerun_status" != "True" ]; then
                     echo "Pipelinerun $pipeline_run_name failed"
-                    failed_pipelines=$((failed_pipelines + 1))
+                    exit 1
                   fi
 
                 ) &
-              done < <(echo "$CONFIGS_JSON" | jq -r '.[][] | select(.key == "OCP").value')
-              wait
-              if [ $failed_pipelines -gt 0 ]; then
-                echo "One or more pipelineruns failed. Exiting with non-zero code."
-                oc get pipelineruns
-                exit 1
-              fi
+                pid="$!"
+                pids+=("$pid")
+              done < <(echo "$CONFIGS_JSON" | jq -r '.[][] | select(.key == "OCP").value');
+              for pid in "${pids[@]}"; do
+                wait "$pid"
+                return_code=$?
+                if [ ! $return_code -eq 0 ]; then
+                  echo "One or more pipelineruns failed. Exiting with non-zero code."
+                  oc get pipelineruns
+                  exit 1
+                fi
+              done
 
